# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('alergies', models.CharField(max_length=200)),
                ('responsable', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
