# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=20)),
                ('maintenance', models.IntegerField(default=0)),
                ('life', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('noise', models.IntegerField(default=0)),
                ('rare', models.CharField(max_length=20)),
            ],
        ),
    ]
