# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rare', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='animals',
            name='life',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Life'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='noise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Noise'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='rare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Rarity'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Size'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Time'),
        ),
    ]
